# Don't block PR merges on coverage deltas, sometimes they're unavoidable in Go
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
