# This file contains custom configuration for Thelma that can be set for running in ArgoCD

autoupdate:
  # Don't auto-update on ArgoCD, that's unproven and for now we'll
  # control Thelma's version with the ArgoCD appVersion from Beehive
  enabled: false

credentials:
  # Might as well cache credentials across runs, since the sidecar
  # will be persistent
  storetype: directory

google:
  auth:
    type: adc
    adc:
      # Will use Google Service Account via Workload Identity
      verifybroademail: false

iap:
  # Use Google auth to generate IAP tokens (will work since the Google
  # auth is via a service account)
  provider: google

logging:
  console:
    level: info
  file:
    enabled: false

vault:
  # Vault auth isn't available when running in ArgoCD (and it's not
  # needed); so we won't declare management of ~/.vault-token
  manageusertoken: false
