# this file contains bleeding-edge configuration for Thelma that can be custom set for running in GitHub Actions

autoupdate:
  # we never want auto-update enabled in CI environments
  enabled: false

credentials:
  # use inmemory store so creds aren't persistent to disk
  storetype: inmemory

github:
  auth:
    type: vault

google:
  auth:
    type: adc
    adc:
      verifybroademail: false

iap:
  # use google auth to generate IAP tokens
  provider: google

logging:
  console:
    level: info
  file:
    # disable file logging
    enabled: false

vault:
  # do not manage ~/.vault-token in ArgoCD/Jenkins/GitHub actions, treat vault token like a regular credential
  manageusertoken: false
