package views

import (
	"github.com/broadinstitute/thelma/internal/thelma/state/api/terra"
	"github.com/broadinstitute/thelma/internal/thelma/state/providers/gitops/statebucket"
)

// BeeSummary struct used for presenting BEEs in yaml & json output
type BeeSummary struct {
	Name string
}

// BeeDetail struct used for presenting BEEs in yaml & json output generated by bee commands
type BeeDetail struct {
	Name             string                           `json:"name"`
	Template         string                           `json:"template"`
	TerraHelmfileRef string                           `json:"terraHelmfileRef,omitempty" yaml:"terraHelmfileRef,omitempty"`
	Overrides        map[string]*statebucket.Override `json:"overrides,omitempty" yaml:",omitempty"`
}

func DescribeBee(bee terra.Environment) BeeDetail {
	e := BeeDetail{
		Name:             bee.Name(),
		TerraHelmfileRef: bee.TerraHelmfileRef(),
		Template:         bee.Template(),
	}

	return e
}

func SummarizeBees(bees []terra.Environment) []BeeSummary {
	var result []BeeSummary
	for _, environment := range bees {
		result = append(result, BeeSummary{
			Name: environment.Name(),
		})
	}
	return result
}

func DescribeBees(bees []terra.Environment, dynamicEnvs []statebucket.DynamicEnvironment) []BeeDetail {
	dynEnvMap := make(map[string]statebucket.DynamicEnvironment)
	for _, dynEnv := range dynamicEnvs {
		dynEnvMap[dynEnv.Name] = dynEnv
	}

	result := make([]BeeDetail, len(bees))

	for i, e := range bees {
		dynEnv, exists := dynEnvMap[e.Name()]
		if exists {
			result[i] = DescribeBeeWithReleaseOverrides(e, dynEnv)
		} else {
			result[i] = DescribeBee(e)
		}
	}

	return result
}

func DescribeBeeWithReleaseOverrides(bee terra.Environment, dynamicEnv statebucket.DynamicEnvironment) BeeDetail {
	view := DescribeBee(bee)
	view.Overrides = dynamicEnv.Overrides
	return view
}
