package views

import (
	"github.com/broadinstitute/thelma/internal/thelma/charts/semver"
	"sort"
	"strings"
)

// Struct used for presenting chart releases in yaml & json output generated by publish & import commands
type ChartRelease struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Repo    string `json:"repo"`
}

func SortChartReleases(releases []ChartRelease) {
	sort.Slice(releases, func(i, j int) bool {
		r1, r2 := releases[i], releases[j]
		return r1.compare(r2) < 0
	})
}

// Compare this chart release (c) with another (c2)
// Returns: -1 if c1 < c2, 0 if c1 == c2, +1 if c1 > c2
func (c ChartRelease) compare(other ChartRelease) int {
	byRepo := strings.Compare(c.Repo, other.Repo)
	if byRepo != 0 {
		return byRepo
	}

	byName := strings.Compare(c.Name, other.Name)
	if byName != 0 {
		return byName
	}

	return semver.Compare(c.Version, other.Version)
}
