// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChartReleaseStatusUpdater is an autogenerated mock type for the ChartReleaseStatusUpdater type
type ChartReleaseStatusUpdater struct {
	mock.Mock
}

type ChartReleaseStatusUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *ChartReleaseStatusUpdater) EXPECT() *ChartReleaseStatusUpdater_Expecter {
	return &ChartReleaseStatusUpdater_Expecter{mock: &_m.Mock}
}

// UpdateChartReleaseStatuses provides a mock function with given fields: chartReleaseStatuses
func (_m *ChartReleaseStatusUpdater) UpdateChartReleaseStatuses(chartReleaseStatuses map[string]string) error {
	ret := _m.Called(chartReleaseStatuses)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChartReleaseStatuses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(chartReleaseStatuses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChartReleaseStatuses'
type ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call struct {
	*mock.Call
}

// UpdateChartReleaseStatuses is a helper method to define mock.On call
//   - chartReleaseStatuses map[string]string
func (_e *ChartReleaseStatusUpdater_Expecter) UpdateChartReleaseStatuses(chartReleaseStatuses interface{}) *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call {
	return &ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call{Call: _e.mock.On("UpdateChartReleaseStatuses", chartReleaseStatuses)}
}

func (_c *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call) Run(run func(chartReleaseStatuses map[string]string)) *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]string))
	})
	return _c
}

func (_c *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call) Return(_a0 error) *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call) RunAndReturn(run func(map[string]string) error) *ChartReleaseStatusUpdater_UpdateChartReleaseStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// NewChartReleaseStatusUpdater creates a new instance of ChartReleaseStatusUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChartReleaseStatusUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChartReleaseStatusUpdater {
	mock := &ChartReleaseStatusUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
