// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChartVersionUpdater is an autogenerated mock type for the ChartVersionUpdater type
type ChartVersionUpdater struct {
	mock.Mock
}

// UpdateForNewChartVersion provides a mock function with given fields: chartSelector, newVersion, lastVersion, description, chartReleaseSelectors
func (_m *ChartVersionUpdater) UpdateForNewChartVersion(chartSelector string, newVersion string, lastVersion string, description string, chartReleaseSelectors ...string) error {
	_va := make([]interface{}, len(chartReleaseSelectors))
	for _i := range chartReleaseSelectors {
		_va[_i] = chartReleaseSelectors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, chartSelector, newVersion, lastVersion, description)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, ...string) error); ok {
		r0 = rf(chartSelector, newVersion, lastVersion, description, chartReleaseSelectors...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewChartVersionUpdater interface {
	mock.TestingT
	Cleanup(func())
}

// NewChartVersionUpdater creates a new instance of ChartVersionUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChartVersionUpdater(t mockConstructorTestingTNewChartVersionUpdater) *ChartVersionUpdater {
	mock := &ChartVersionUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
