// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	sherlock "github.com/broadinstitute/thelma/internal/thelma/clients/sherlock"
	terra "github.com/broadinstitute/thelma/internal/thelma/state/api/terra"
	mock "github.com/stretchr/testify/mock"
)

// SherlockClient is an autogenerated mock type for the SherlockClient type
type SherlockClient struct {
	mock.Mock
}

type SherlockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SherlockClient) EXPECT() *SherlockClient_Expecter {
	return &SherlockClient_Expecter{mock: &_m.Mock}
}

// Clusters provides a mock function with given fields:
func (_m *SherlockClient) Clusters() (sherlock.Clusters, error) {
	ret := _m.Called()

	var r0 sherlock.Clusters
	var r1 error
	if rf, ok := ret.Get(0).(func() (sherlock.Clusters, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() sherlock.Clusters); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sherlock.Clusters)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SherlockClient_Clusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clusters'
type SherlockClient_Clusters_Call struct {
	*mock.Call
}

// Clusters is a helper method to define mock.On call
func (_e *SherlockClient_Expecter) Clusters() *SherlockClient_Clusters_Call {
	return &SherlockClient_Clusters_Call{Call: _e.mock.On("Clusters")}
}

func (_c *SherlockClient_Clusters_Call) Run(run func()) *SherlockClient_Clusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SherlockClient_Clusters_Call) Return(_a0 sherlock.Clusters, _a1 error) *SherlockClient_Clusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SherlockClient_Clusters_Call) RunAndReturn(run func() (sherlock.Clusters, error)) *SherlockClient_Clusters_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEnvironmentFromTemplate provides a mock function with given fields: templateName, options
func (_m *SherlockClient) CreateEnvironmentFromTemplate(templateName string, options terra.CreateOptions) (string, error) {
	ret := _m.Called(templateName, options)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, terra.CreateOptions) (string, error)); ok {
		return rf(templateName, options)
	}
	if rf, ok := ret.Get(0).(func(string, terra.CreateOptions) string); ok {
		r0 = rf(templateName, options)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, terra.CreateOptions) error); ok {
		r1 = rf(templateName, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SherlockClient_CreateEnvironmentFromTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEnvironmentFromTemplate'
type SherlockClient_CreateEnvironmentFromTemplate_Call struct {
	*mock.Call
}

// CreateEnvironmentFromTemplate is a helper method to define mock.On call
//   - templateName string
//   - options terra.CreateOptions
func (_e *SherlockClient_Expecter) CreateEnvironmentFromTemplate(templateName interface{}, options interface{}) *SherlockClient_CreateEnvironmentFromTemplate_Call {
	return &SherlockClient_CreateEnvironmentFromTemplate_Call{Call: _e.mock.On("CreateEnvironmentFromTemplate", templateName, options)}
}

func (_c *SherlockClient_CreateEnvironmentFromTemplate_Call) Run(run func(templateName string, options terra.CreateOptions)) *SherlockClient_CreateEnvironmentFromTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(terra.CreateOptions))
	})
	return _c
}

func (_c *SherlockClient_CreateEnvironmentFromTemplate_Call) Return(_a0 string, _a1 error) *SherlockClient_CreateEnvironmentFromTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SherlockClient_CreateEnvironmentFromTemplate_Call) RunAndReturn(run func(string, terra.CreateOptions) (string, error)) *SherlockClient_CreateEnvironmentFromTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEnvironments provides a mock function with given fields: _a0
func (_m *SherlockClient) DeleteEnvironments(_a0 []terra.Environment) ([]string, error) {
	ret := _m.Called(_a0)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func([]terra.Environment) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]terra.Environment) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func([]terra.Environment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SherlockClient_DeleteEnvironments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEnvironments'
type SherlockClient_DeleteEnvironments_Call struct {
	*mock.Call
}

// DeleteEnvironments is a helper method to define mock.On call
//   - _a0 []terra.Environment
func (_e *SherlockClient_Expecter) DeleteEnvironments(_a0 interface{}) *SherlockClient_DeleteEnvironments_Call {
	return &SherlockClient_DeleteEnvironments_Call{Call: _e.mock.On("DeleteEnvironments", _a0)}
}

func (_c *SherlockClient_DeleteEnvironments_Call) Run(run func(_a0 []terra.Environment)) *SherlockClient_DeleteEnvironments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]terra.Environment))
	})
	return _c
}

func (_c *SherlockClient_DeleteEnvironments_Call) Return(_a0 []string, _a1 error) *SherlockClient_DeleteEnvironments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SherlockClient_DeleteEnvironments_Call) RunAndReturn(run func([]terra.Environment) ([]string, error)) *SherlockClient_DeleteEnvironments_Call {
	_c.Call.Return(run)
	return _c
}

// DisableRelease provides a mock function with given fields: _a0, _a1
func (_m *SherlockClient) DisableRelease(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_DisableRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableRelease'
type SherlockClient_DisableRelease_Call struct {
	*mock.Call
}

// DisableRelease is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *SherlockClient_Expecter) DisableRelease(_a0 interface{}, _a1 interface{}) *SherlockClient_DisableRelease_Call {
	return &SherlockClient_DisableRelease_Call{Call: _e.mock.On("DisableRelease", _a0, _a1)}
}

func (_c *SherlockClient_DisableRelease_Call) Run(run func(_a0 string, _a1 string)) *SherlockClient_DisableRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *SherlockClient_DisableRelease_Call) Return(_a0 error) *SherlockClient_DisableRelease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_DisableRelease_Call) RunAndReturn(run func(string, string) error) *SherlockClient_DisableRelease_Call {
	_c.Call.Return(run)
	return _c
}

// EnableRelease provides a mock function with given fields: _a0, _a1
func (_m *SherlockClient) EnableRelease(_a0 terra.Environment, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(terra.Environment, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_EnableRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableRelease'
type SherlockClient_EnableRelease_Call struct {
	*mock.Call
}

// EnableRelease is a helper method to define mock.On call
//   - _a0 terra.Environment
//   - _a1 string
func (_e *SherlockClient_Expecter) EnableRelease(_a0 interface{}, _a1 interface{}) *SherlockClient_EnableRelease_Call {
	return &SherlockClient_EnableRelease_Call{Call: _e.mock.On("EnableRelease", _a0, _a1)}
}

func (_c *SherlockClient_EnableRelease_Call) Run(run func(_a0 terra.Environment, _a1 string)) *SherlockClient_EnableRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(terra.Environment), args[1].(string))
	})
	return _c
}

func (_c *SherlockClient_EnableRelease_Call) Return(_a0 error) *SherlockClient_EnableRelease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_EnableRelease_Call) RunAndReturn(run func(terra.Environment, string) error) *SherlockClient_EnableRelease_Call {
	_c.Call.Return(run)
	return _c
}

// Environments provides a mock function with given fields:
func (_m *SherlockClient) Environments() (sherlock.Environments, error) {
	ret := _m.Called()

	var r0 sherlock.Environments
	var r1 error
	if rf, ok := ret.Get(0).(func() (sherlock.Environments, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() sherlock.Environments); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sherlock.Environments)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SherlockClient_Environments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Environments'
type SherlockClient_Environments_Call struct {
	*mock.Call
}

// Environments is a helper method to define mock.On call
func (_e *SherlockClient_Expecter) Environments() *SherlockClient_Environments_Call {
	return &SherlockClient_Environments_Call{Call: _e.mock.On("Environments")}
}

func (_c *SherlockClient_Environments_Call) Run(run func()) *SherlockClient_Environments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SherlockClient_Environments_Call) Return(_a0 sherlock.Environments, _a1 error) *SherlockClient_Environments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SherlockClient_Environments_Call) RunAndReturn(run func() (sherlock.Environments, error)) *SherlockClient_Environments_Call {
	_c.Call.Return(run)
	return _c
}

// PinEnvironmentVersions provides a mock function with given fields: environmentName, versions
func (_m *SherlockClient) PinEnvironmentVersions(environmentName string, versions map[string]terra.VersionOverride) error {
	ret := _m.Called(environmentName, versions)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]terra.VersionOverride) error); ok {
		r0 = rf(environmentName, versions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_PinEnvironmentVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PinEnvironmentVersions'
type SherlockClient_PinEnvironmentVersions_Call struct {
	*mock.Call
}

// PinEnvironmentVersions is a helper method to define mock.On call
//   - environmentName string
//   - versions map[string]terra.VersionOverride
func (_e *SherlockClient_Expecter) PinEnvironmentVersions(environmentName interface{}, versions interface{}) *SherlockClient_PinEnvironmentVersions_Call {
	return &SherlockClient_PinEnvironmentVersions_Call{Call: _e.mock.On("PinEnvironmentVersions", environmentName, versions)}
}

func (_c *SherlockClient_PinEnvironmentVersions_Call) Run(run func(environmentName string, versions map[string]terra.VersionOverride)) *SherlockClient_PinEnvironmentVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]terra.VersionOverride))
	})
	return _c
}

func (_c *SherlockClient_PinEnvironmentVersions_Call) Return(_a0 error) *SherlockClient_PinEnvironmentVersions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_PinEnvironmentVersions_Call) RunAndReturn(run func(string, map[string]terra.VersionOverride) error) *SherlockClient_PinEnvironmentVersions_Call {
	_c.Call.Return(run)
	return _c
}

// Releases provides a mock function with given fields:
func (_m *SherlockClient) Releases() (sherlock.Releases, error) {
	ret := _m.Called()

	var r0 sherlock.Releases
	var r1 error
	if rf, ok := ret.Get(0).(func() (sherlock.Releases, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() sherlock.Releases); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sherlock.Releases)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SherlockClient_Releases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Releases'
type SherlockClient_Releases_Call struct {
	*mock.Call
}

// Releases is a helper method to define mock.On call
func (_e *SherlockClient_Expecter) Releases() *SherlockClient_Releases_Call {
	return &SherlockClient_Releases_Call{Call: _e.mock.On("Releases")}
}

func (_c *SherlockClient_Releases_Call) Run(run func()) *SherlockClient_Releases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SherlockClient_Releases_Call) Return(_a0 sherlock.Releases, _a1 error) *SherlockClient_Releases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SherlockClient_Releases_Call) RunAndReturn(run func() (sherlock.Releases, error)) *SherlockClient_Releases_Call {
	_c.Call.Return(run)
	return _c
}

// ResetEnvironmentAndPinToDev provides a mock function with given fields: environment
func (_m *SherlockClient) ResetEnvironmentAndPinToDev(environment terra.Environment) error {
	ret := _m.Called(environment)

	var r0 error
	if rf, ok := ret.Get(0).(func(terra.Environment) error); ok {
		r0 = rf(environment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_ResetEnvironmentAndPinToDev_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetEnvironmentAndPinToDev'
type SherlockClient_ResetEnvironmentAndPinToDev_Call struct {
	*mock.Call
}

// ResetEnvironmentAndPinToDev is a helper method to define mock.On call
//   - environment terra.Environment
func (_e *SherlockClient_Expecter) ResetEnvironmentAndPinToDev(environment interface{}) *SherlockClient_ResetEnvironmentAndPinToDev_Call {
	return &SherlockClient_ResetEnvironmentAndPinToDev_Call{Call: _e.mock.On("ResetEnvironmentAndPinToDev", environment)}
}

func (_c *SherlockClient_ResetEnvironmentAndPinToDev_Call) Run(run func(environment terra.Environment)) *SherlockClient_ResetEnvironmentAndPinToDev_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(terra.Environment))
	})
	return _c
}

func (_c *SherlockClient_ResetEnvironmentAndPinToDev_Call) Return(_a0 error) *SherlockClient_ResetEnvironmentAndPinToDev_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_ResetEnvironmentAndPinToDev_Call) RunAndReturn(run func(terra.Environment) error) *SherlockClient_ResetEnvironmentAndPinToDev_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnvironmentOffline provides a mock function with given fields: environmentName, offline
func (_m *SherlockClient) SetEnvironmentOffline(environmentName string, offline bool) error {
	ret := _m.Called(environmentName, offline)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(environmentName, offline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_SetEnvironmentOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvironmentOffline'
type SherlockClient_SetEnvironmentOffline_Call struct {
	*mock.Call
}

// SetEnvironmentOffline is a helper method to define mock.On call
//   - environmentName string
//   - offline bool
func (_e *SherlockClient_Expecter) SetEnvironmentOffline(environmentName interface{}, offline interface{}) *SherlockClient_SetEnvironmentOffline_Call {
	return &SherlockClient_SetEnvironmentOffline_Call{Call: _e.mock.On("SetEnvironmentOffline", environmentName, offline)}
}

func (_c *SherlockClient_SetEnvironmentOffline_Call) Run(run func(environmentName string, offline bool)) *SherlockClient_SetEnvironmentOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *SherlockClient_SetEnvironmentOffline_Call) Return(_a0 error) *SherlockClient_SetEnvironmentOffline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_SetEnvironmentOffline_Call) RunAndReturn(run func(string, bool) error) *SherlockClient_SetEnvironmentOffline_Call {
	_c.Call.Return(run)
	return _c
}

// SetTerraHelmfileRefForEntireEnvironment provides a mock function with given fields: environment, terraHelmfileRef
func (_m *SherlockClient) SetTerraHelmfileRefForEntireEnvironment(environment terra.Environment, terraHelmfileRef string) error {
	ret := _m.Called(environment, terraHelmfileRef)

	var r0 error
	if rf, ok := ret.Get(0).(func(terra.Environment, string) error); ok {
		r0 = rf(environment, terraHelmfileRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTerraHelmfileRefForEntireEnvironment'
type SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call struct {
	*mock.Call
}

// SetTerraHelmfileRefForEntireEnvironment is a helper method to define mock.On call
//   - environment terra.Environment
//   - terraHelmfileRef string
func (_e *SherlockClient_Expecter) SetTerraHelmfileRefForEntireEnvironment(environment interface{}, terraHelmfileRef interface{}) *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call {
	return &SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call{Call: _e.mock.On("SetTerraHelmfileRefForEntireEnvironment", environment, terraHelmfileRef)}
}

func (_c *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call) Run(run func(environment terra.Environment, terraHelmfileRef string)) *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(terra.Environment), args[1].(string))
	})
	return _c
}

func (_c *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call) Return(_a0 error) *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call) RunAndReturn(run func(terra.Environment, string) error) *SherlockClient_SetTerraHelmfileRefForEntireEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateForNewChartVersion provides a mock function with given fields: chartSelector, newVersion, lastVersion, description, chartReleaseSelectors
func (_m *SherlockClient) UpdateForNewChartVersion(chartSelector string, newVersion string, lastVersion string, description string, chartReleaseSelectors ...string) error {
	_va := make([]interface{}, len(chartReleaseSelectors))
	for _i := range chartReleaseSelectors {
		_va[_i] = chartReleaseSelectors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, chartSelector, newVersion, lastVersion, description)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, ...string) error); ok {
		r0 = rf(chartSelector, newVersion, lastVersion, description, chartReleaseSelectors...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_UpdateForNewChartVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateForNewChartVersion'
type SherlockClient_UpdateForNewChartVersion_Call struct {
	*mock.Call
}

// UpdateForNewChartVersion is a helper method to define mock.On call
//   - chartSelector string
//   - newVersion string
//   - lastVersion string
//   - description string
//   - chartReleaseSelectors ...string
func (_e *SherlockClient_Expecter) UpdateForNewChartVersion(chartSelector interface{}, newVersion interface{}, lastVersion interface{}, description interface{}, chartReleaseSelectors ...interface{}) *SherlockClient_UpdateForNewChartVersion_Call {
	return &SherlockClient_UpdateForNewChartVersion_Call{Call: _e.mock.On("UpdateForNewChartVersion",
		append([]interface{}{chartSelector, newVersion, lastVersion, description}, chartReleaseSelectors...)...)}
}

func (_c *SherlockClient_UpdateForNewChartVersion_Call) Run(run func(chartSelector string, newVersion string, lastVersion string, description string, chartReleaseSelectors ...string)) *SherlockClient_UpdateForNewChartVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), variadicArgs...)
	})
	return _c
}

func (_c *SherlockClient_UpdateForNewChartVersion_Call) Return(_a0 error) *SherlockClient_UpdateForNewChartVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_UpdateForNewChartVersion_Call) RunAndReturn(run func(string, string, string, string, ...string) error) *SherlockClient_UpdateForNewChartVersion_Call {
	_c.Call.Return(run)
	return _c
}

// WriteClusters provides a mock function with given fields: _a0
func (_m *SherlockClient) WriteClusters(_a0 []terra.Cluster) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]terra.Cluster) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_WriteClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteClusters'
type SherlockClient_WriteClusters_Call struct {
	*mock.Call
}

// WriteClusters is a helper method to define mock.On call
//   - _a0 []terra.Cluster
func (_e *SherlockClient_Expecter) WriteClusters(_a0 interface{}) *SherlockClient_WriteClusters_Call {
	return &SherlockClient_WriteClusters_Call{Call: _e.mock.On("WriteClusters", _a0)}
}

func (_c *SherlockClient_WriteClusters_Call) Run(run func(_a0 []terra.Cluster)) *SherlockClient_WriteClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]terra.Cluster))
	})
	return _c
}

func (_c *SherlockClient_WriteClusters_Call) Return(_a0 error) *SherlockClient_WriteClusters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_WriteClusters_Call) RunAndReturn(run func([]terra.Cluster) error) *SherlockClient_WriteClusters_Call {
	_c.Call.Return(run)
	return _c
}

// WriteEnvironments provides a mock function with given fields: _a0
func (_m *SherlockClient) WriteEnvironments(_a0 []terra.Environment) ([]string, error) {
	ret := _m.Called(_a0)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func([]terra.Environment) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]terra.Environment) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func([]terra.Environment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SherlockClient_WriteEnvironments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteEnvironments'
type SherlockClient_WriteEnvironments_Call struct {
	*mock.Call
}

// WriteEnvironments is a helper method to define mock.On call
//   - _a0 []terra.Environment
func (_e *SherlockClient_Expecter) WriteEnvironments(_a0 interface{}) *SherlockClient_WriteEnvironments_Call {
	return &SherlockClient_WriteEnvironments_Call{Call: _e.mock.On("WriteEnvironments", _a0)}
}

func (_c *SherlockClient_WriteEnvironments_Call) Run(run func(_a0 []terra.Environment)) *SherlockClient_WriteEnvironments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]terra.Environment))
	})
	return _c
}

func (_c *SherlockClient_WriteEnvironments_Call) Return(_a0 []string, _a1 error) *SherlockClient_WriteEnvironments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SherlockClient_WriteEnvironments_Call) RunAndReturn(run func([]terra.Environment) ([]string, error)) *SherlockClient_WriteEnvironments_Call {
	_c.Call.Return(run)
	return _c
}

// getStatus provides a mock function with given fields:
func (_m *SherlockClient) getStatus() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SherlockClient_getStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getStatus'
type SherlockClient_getStatus_Call struct {
	*mock.Call
}

// getStatus is a helper method to define mock.On call
func (_e *SherlockClient_Expecter) getStatus() *SherlockClient_getStatus_Call {
	return &SherlockClient_getStatus_Call{Call: _e.mock.On("getStatus")}
}

func (_c *SherlockClient_getStatus_Call) Run(run func()) *SherlockClient_getStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SherlockClient_getStatus_Call) Return(_a0 error) *SherlockClient_getStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SherlockClient_getStatus_Call) RunAndReturn(run func() error) *SherlockClient_getStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewSherlockClient creates a new instance of SherlockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSherlockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SherlockClient {
	mock := &SherlockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
