// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	containerpb "cloud.google.com/go/container/apiv1/containerpb"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"
)

// ClusterManagerServer is an autogenerated mock type for the ClusterManagerServer type
type ClusterManagerServer struct {
	mock.Mock
}

type ClusterManagerServer_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterManagerServer) EXPECT() *ClusterManagerServer_Expecter {
	return &ClusterManagerServer_Expecter{mock: &_m.Mock}
}

// CancelOperation provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) CancelOperation(_a0 context.Context, _a1 *containerpb.CancelOperationRequest) (*emptypb.Empty, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *emptypb.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.CancelOperationRequest) *emptypb.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.CancelOperationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_CancelOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOperation'
type ClusterManagerServer_CancelOperation_Call struct {
	*mock.Call
}

// CancelOperation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.CancelOperationRequest
func (_e *ClusterManagerServer_Expecter) CancelOperation(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_CancelOperation_Call {
	return &ClusterManagerServer_CancelOperation_Call{Call: _e.mock.On("CancelOperation", _a0, _a1)}
}

func (_c *ClusterManagerServer_CancelOperation_Call) Run(run func(_a0 context.Context, _a1 *containerpb.CancelOperationRequest)) *ClusterManagerServer_CancelOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.CancelOperationRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_CancelOperation_Call) Return(_a0 *emptypb.Empty, _a1 error) *ClusterManagerServer_CancelOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CompleteIPRotation provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) CompleteIPRotation(_a0 context.Context, _a1 *containerpb.CompleteIPRotationRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.CompleteIPRotationRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.CompleteIPRotationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_CompleteIPRotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteIPRotation'
type ClusterManagerServer_CompleteIPRotation_Call struct {
	*mock.Call
}

// CompleteIPRotation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.CompleteIPRotationRequest
func (_e *ClusterManagerServer_Expecter) CompleteIPRotation(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_CompleteIPRotation_Call {
	return &ClusterManagerServer_CompleteIPRotation_Call{Call: _e.mock.On("CompleteIPRotation", _a0, _a1)}
}

func (_c *ClusterManagerServer_CompleteIPRotation_Call) Run(run func(_a0 context.Context, _a1 *containerpb.CompleteIPRotationRequest)) *ClusterManagerServer_CompleteIPRotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.CompleteIPRotationRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_CompleteIPRotation_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_CompleteIPRotation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CompleteNodePoolUpgrade provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) CompleteNodePoolUpgrade(_a0 context.Context, _a1 *containerpb.CompleteNodePoolUpgradeRequest) (*emptypb.Empty, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *emptypb.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.CompleteNodePoolUpgradeRequest) *emptypb.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.CompleteNodePoolUpgradeRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_CompleteNodePoolUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteNodePoolUpgrade'
type ClusterManagerServer_CompleteNodePoolUpgrade_Call struct {
	*mock.Call
}

// CompleteNodePoolUpgrade is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.CompleteNodePoolUpgradeRequest
func (_e *ClusterManagerServer_Expecter) CompleteNodePoolUpgrade(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_CompleteNodePoolUpgrade_Call {
	return &ClusterManagerServer_CompleteNodePoolUpgrade_Call{Call: _e.mock.On("CompleteNodePoolUpgrade", _a0, _a1)}
}

func (_c *ClusterManagerServer_CompleteNodePoolUpgrade_Call) Run(run func(_a0 context.Context, _a1 *containerpb.CompleteNodePoolUpgradeRequest)) *ClusterManagerServer_CompleteNodePoolUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.CompleteNodePoolUpgradeRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_CompleteNodePoolUpgrade_Call) Return(_a0 *emptypb.Empty, _a1 error) *ClusterManagerServer_CompleteNodePoolUpgrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateCluster provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) CreateCluster(_a0 context.Context, _a1 *containerpb.CreateClusterRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.CreateClusterRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.CreateClusterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type ClusterManagerServer_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.CreateClusterRequest
func (_e *ClusterManagerServer_Expecter) CreateCluster(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_CreateCluster_Call {
	return &ClusterManagerServer_CreateCluster_Call{Call: _e.mock.On("CreateCluster", _a0, _a1)}
}

func (_c *ClusterManagerServer_CreateCluster_Call) Run(run func(_a0 context.Context, _a1 *containerpb.CreateClusterRequest)) *ClusterManagerServer_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.CreateClusterRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_CreateCluster_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_CreateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateNodePool provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) CreateNodePool(_a0 context.Context, _a1 *containerpb.CreateNodePoolRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.CreateNodePoolRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.CreateNodePoolRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_CreateNodePool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNodePool'
type ClusterManagerServer_CreateNodePool_Call struct {
	*mock.Call
}

// CreateNodePool is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.CreateNodePoolRequest
func (_e *ClusterManagerServer_Expecter) CreateNodePool(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_CreateNodePool_Call {
	return &ClusterManagerServer_CreateNodePool_Call{Call: _e.mock.On("CreateNodePool", _a0, _a1)}
}

func (_c *ClusterManagerServer_CreateNodePool_Call) Run(run func(_a0 context.Context, _a1 *containerpb.CreateNodePoolRequest)) *ClusterManagerServer_CreateNodePool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.CreateNodePoolRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_CreateNodePool_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_CreateNodePool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteCluster provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) DeleteCluster(_a0 context.Context, _a1 *containerpb.DeleteClusterRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.DeleteClusterRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.DeleteClusterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type ClusterManagerServer_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.DeleteClusterRequest
func (_e *ClusterManagerServer_Expecter) DeleteCluster(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_DeleteCluster_Call {
	return &ClusterManagerServer_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", _a0, _a1)}
}

func (_c *ClusterManagerServer_DeleteCluster_Call) Run(run func(_a0 context.Context, _a1 *containerpb.DeleteClusterRequest)) *ClusterManagerServer_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.DeleteClusterRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_DeleteCluster_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_DeleteCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteNodePool provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) DeleteNodePool(_a0 context.Context, _a1 *containerpb.DeleteNodePoolRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.DeleteNodePoolRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.DeleteNodePoolRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_DeleteNodePool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNodePool'
type ClusterManagerServer_DeleteNodePool_Call struct {
	*mock.Call
}

// DeleteNodePool is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.DeleteNodePoolRequest
func (_e *ClusterManagerServer_Expecter) DeleteNodePool(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_DeleteNodePool_Call {
	return &ClusterManagerServer_DeleteNodePool_Call{Call: _e.mock.On("DeleteNodePool", _a0, _a1)}
}

func (_c *ClusterManagerServer_DeleteNodePool_Call) Run(run func(_a0 context.Context, _a1 *containerpb.DeleteNodePoolRequest)) *ClusterManagerServer_DeleteNodePool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.DeleteNodePoolRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_DeleteNodePool_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_DeleteNodePool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetCluster provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) GetCluster(_a0 context.Context, _a1 *containerpb.GetClusterRequest) (*containerpb.Cluster, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Cluster
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.GetClusterRequest) *containerpb.Cluster); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Cluster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.GetClusterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type ClusterManagerServer_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.GetClusterRequest
func (_e *ClusterManagerServer_Expecter) GetCluster(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_GetCluster_Call {
	return &ClusterManagerServer_GetCluster_Call{Call: _e.mock.On("GetCluster", _a0, _a1)}
}

func (_c *ClusterManagerServer_GetCluster_Call) Run(run func(_a0 context.Context, _a1 *containerpb.GetClusterRequest)) *ClusterManagerServer_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.GetClusterRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_GetCluster_Call) Return(_a0 *containerpb.Cluster, _a1 error) *ClusterManagerServer_GetCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetJSONWebKeys provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) GetJSONWebKeys(_a0 context.Context, _a1 *containerpb.GetJSONWebKeysRequest) (*containerpb.GetJSONWebKeysResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.GetJSONWebKeysResponse
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.GetJSONWebKeysRequest) *containerpb.GetJSONWebKeysResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.GetJSONWebKeysResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.GetJSONWebKeysRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_GetJSONWebKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJSONWebKeys'
type ClusterManagerServer_GetJSONWebKeys_Call struct {
	*mock.Call
}

// GetJSONWebKeys is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.GetJSONWebKeysRequest
func (_e *ClusterManagerServer_Expecter) GetJSONWebKeys(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_GetJSONWebKeys_Call {
	return &ClusterManagerServer_GetJSONWebKeys_Call{Call: _e.mock.On("GetJSONWebKeys", _a0, _a1)}
}

func (_c *ClusterManagerServer_GetJSONWebKeys_Call) Run(run func(_a0 context.Context, _a1 *containerpb.GetJSONWebKeysRequest)) *ClusterManagerServer_GetJSONWebKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.GetJSONWebKeysRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_GetJSONWebKeys_Call) Return(_a0 *containerpb.GetJSONWebKeysResponse, _a1 error) *ClusterManagerServer_GetJSONWebKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetNodePool provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) GetNodePool(_a0 context.Context, _a1 *containerpb.GetNodePoolRequest) (*containerpb.NodePool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.NodePool
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.GetNodePoolRequest) *containerpb.NodePool); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.NodePool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.GetNodePoolRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_GetNodePool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodePool'
type ClusterManagerServer_GetNodePool_Call struct {
	*mock.Call
}

// GetNodePool is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.GetNodePoolRequest
func (_e *ClusterManagerServer_Expecter) GetNodePool(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_GetNodePool_Call {
	return &ClusterManagerServer_GetNodePool_Call{Call: _e.mock.On("GetNodePool", _a0, _a1)}
}

func (_c *ClusterManagerServer_GetNodePool_Call) Run(run func(_a0 context.Context, _a1 *containerpb.GetNodePoolRequest)) *ClusterManagerServer_GetNodePool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.GetNodePoolRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_GetNodePool_Call) Return(_a0 *containerpb.NodePool, _a1 error) *ClusterManagerServer_GetNodePool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetOperation provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) GetOperation(_a0 context.Context, _a1 *containerpb.GetOperationRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.GetOperationRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.GetOperationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type ClusterManagerServer_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.GetOperationRequest
func (_e *ClusterManagerServer_Expecter) GetOperation(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_GetOperation_Call {
	return &ClusterManagerServer_GetOperation_Call{Call: _e.mock.On("GetOperation", _a0, _a1)}
}

func (_c *ClusterManagerServer_GetOperation_Call) Run(run func(_a0 context.Context, _a1 *containerpb.GetOperationRequest)) *ClusterManagerServer_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.GetOperationRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_GetOperation_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_GetOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetServerConfig provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) GetServerConfig(_a0 context.Context, _a1 *containerpb.GetServerConfigRequest) (*containerpb.ServerConfig, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.ServerConfig
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.GetServerConfigRequest) *containerpb.ServerConfig); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.ServerConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.GetServerConfigRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_GetServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerConfig'
type ClusterManagerServer_GetServerConfig_Call struct {
	*mock.Call
}

// GetServerConfig is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.GetServerConfigRequest
func (_e *ClusterManagerServer_Expecter) GetServerConfig(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_GetServerConfig_Call {
	return &ClusterManagerServer_GetServerConfig_Call{Call: _e.mock.On("GetServerConfig", _a0, _a1)}
}

func (_c *ClusterManagerServer_GetServerConfig_Call) Run(run func(_a0 context.Context, _a1 *containerpb.GetServerConfigRequest)) *ClusterManagerServer_GetServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.GetServerConfigRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_GetServerConfig_Call) Return(_a0 *containerpb.ServerConfig, _a1 error) *ClusterManagerServer_GetServerConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListClusters provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) ListClusters(_a0 context.Context, _a1 *containerpb.ListClustersRequest) (*containerpb.ListClustersResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.ListClustersResponse
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.ListClustersRequest) *containerpb.ListClustersResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.ListClustersResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.ListClustersRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type ClusterManagerServer_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.ListClustersRequest
func (_e *ClusterManagerServer_Expecter) ListClusters(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_ListClusters_Call {
	return &ClusterManagerServer_ListClusters_Call{Call: _e.mock.On("ListClusters", _a0, _a1)}
}

func (_c *ClusterManagerServer_ListClusters_Call) Run(run func(_a0 context.Context, _a1 *containerpb.ListClustersRequest)) *ClusterManagerServer_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.ListClustersRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_ListClusters_Call) Return(_a0 *containerpb.ListClustersResponse, _a1 error) *ClusterManagerServer_ListClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListNodePools provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) ListNodePools(_a0 context.Context, _a1 *containerpb.ListNodePoolsRequest) (*containerpb.ListNodePoolsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.ListNodePoolsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.ListNodePoolsRequest) *containerpb.ListNodePoolsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.ListNodePoolsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.ListNodePoolsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_ListNodePools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodePools'
type ClusterManagerServer_ListNodePools_Call struct {
	*mock.Call
}

// ListNodePools is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.ListNodePoolsRequest
func (_e *ClusterManagerServer_Expecter) ListNodePools(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_ListNodePools_Call {
	return &ClusterManagerServer_ListNodePools_Call{Call: _e.mock.On("ListNodePools", _a0, _a1)}
}

func (_c *ClusterManagerServer_ListNodePools_Call) Run(run func(_a0 context.Context, _a1 *containerpb.ListNodePoolsRequest)) *ClusterManagerServer_ListNodePools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.ListNodePoolsRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_ListNodePools_Call) Return(_a0 *containerpb.ListNodePoolsResponse, _a1 error) *ClusterManagerServer_ListNodePools_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListOperations provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) ListOperations(_a0 context.Context, _a1 *containerpb.ListOperationsRequest) (*containerpb.ListOperationsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.ListOperationsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.ListOperationsRequest) *containerpb.ListOperationsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.ListOperationsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.ListOperationsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_ListOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOperations'
type ClusterManagerServer_ListOperations_Call struct {
	*mock.Call
}

// ListOperations is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.ListOperationsRequest
func (_e *ClusterManagerServer_Expecter) ListOperations(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_ListOperations_Call {
	return &ClusterManagerServer_ListOperations_Call{Call: _e.mock.On("ListOperations", _a0, _a1)}
}

func (_c *ClusterManagerServer_ListOperations_Call) Run(run func(_a0 context.Context, _a1 *containerpb.ListOperationsRequest)) *ClusterManagerServer_ListOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.ListOperationsRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_ListOperations_Call) Return(_a0 *containerpb.ListOperationsResponse, _a1 error) *ClusterManagerServer_ListOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListUsableSubnetworks provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) ListUsableSubnetworks(_a0 context.Context, _a1 *containerpb.ListUsableSubnetworksRequest) (*containerpb.ListUsableSubnetworksResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.ListUsableSubnetworksResponse
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.ListUsableSubnetworksRequest) *containerpb.ListUsableSubnetworksResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.ListUsableSubnetworksResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.ListUsableSubnetworksRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_ListUsableSubnetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsableSubnetworks'
type ClusterManagerServer_ListUsableSubnetworks_Call struct {
	*mock.Call
}

// ListUsableSubnetworks is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.ListUsableSubnetworksRequest
func (_e *ClusterManagerServer_Expecter) ListUsableSubnetworks(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_ListUsableSubnetworks_Call {
	return &ClusterManagerServer_ListUsableSubnetworks_Call{Call: _e.mock.On("ListUsableSubnetworks", _a0, _a1)}
}

func (_c *ClusterManagerServer_ListUsableSubnetworks_Call) Run(run func(_a0 context.Context, _a1 *containerpb.ListUsableSubnetworksRequest)) *ClusterManagerServer_ListUsableSubnetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.ListUsableSubnetworksRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_ListUsableSubnetworks_Call) Return(_a0 *containerpb.ListUsableSubnetworksResponse, _a1 error) *ClusterManagerServer_ListUsableSubnetworks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RollbackNodePoolUpgrade provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) RollbackNodePoolUpgrade(_a0 context.Context, _a1 *containerpb.RollbackNodePoolUpgradeRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.RollbackNodePoolUpgradeRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.RollbackNodePoolUpgradeRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_RollbackNodePoolUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackNodePoolUpgrade'
type ClusterManagerServer_RollbackNodePoolUpgrade_Call struct {
	*mock.Call
}

// RollbackNodePoolUpgrade is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.RollbackNodePoolUpgradeRequest
func (_e *ClusterManagerServer_Expecter) RollbackNodePoolUpgrade(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_RollbackNodePoolUpgrade_Call {
	return &ClusterManagerServer_RollbackNodePoolUpgrade_Call{Call: _e.mock.On("RollbackNodePoolUpgrade", _a0, _a1)}
}

func (_c *ClusterManagerServer_RollbackNodePoolUpgrade_Call) Run(run func(_a0 context.Context, _a1 *containerpb.RollbackNodePoolUpgradeRequest)) *ClusterManagerServer_RollbackNodePoolUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.RollbackNodePoolUpgradeRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_RollbackNodePoolUpgrade_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_RollbackNodePoolUpgrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetAddonsConfig provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetAddonsConfig(_a0 context.Context, _a1 *containerpb.SetAddonsConfigRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetAddonsConfigRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetAddonsConfigRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetAddonsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAddonsConfig'
type ClusterManagerServer_SetAddonsConfig_Call struct {
	*mock.Call
}

// SetAddonsConfig is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetAddonsConfigRequest
func (_e *ClusterManagerServer_Expecter) SetAddonsConfig(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetAddonsConfig_Call {
	return &ClusterManagerServer_SetAddonsConfig_Call{Call: _e.mock.On("SetAddonsConfig", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetAddonsConfig_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetAddonsConfigRequest)) *ClusterManagerServer_SetAddonsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetAddonsConfigRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetAddonsConfig_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetAddonsConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetLabels provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetLabels(_a0 context.Context, _a1 *containerpb.SetLabelsRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetLabelsRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetLabelsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type ClusterManagerServer_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetLabelsRequest
func (_e *ClusterManagerServer_Expecter) SetLabels(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetLabels_Call {
	return &ClusterManagerServer_SetLabels_Call{Call: _e.mock.On("SetLabels", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetLabels_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetLabelsRequest)) *ClusterManagerServer_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetLabelsRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetLabels_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetLabels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetLegacyAbac provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetLegacyAbac(_a0 context.Context, _a1 *containerpb.SetLegacyAbacRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetLegacyAbacRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetLegacyAbacRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetLegacyAbac_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLegacyAbac'
type ClusterManagerServer_SetLegacyAbac_Call struct {
	*mock.Call
}

// SetLegacyAbac is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetLegacyAbacRequest
func (_e *ClusterManagerServer_Expecter) SetLegacyAbac(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetLegacyAbac_Call {
	return &ClusterManagerServer_SetLegacyAbac_Call{Call: _e.mock.On("SetLegacyAbac", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetLegacyAbac_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetLegacyAbacRequest)) *ClusterManagerServer_SetLegacyAbac_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetLegacyAbacRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetLegacyAbac_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetLegacyAbac_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetLocations provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetLocations(_a0 context.Context, _a1 *containerpb.SetLocationsRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetLocationsRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetLocationsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLocations'
type ClusterManagerServer_SetLocations_Call struct {
	*mock.Call
}

// SetLocations is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetLocationsRequest
func (_e *ClusterManagerServer_Expecter) SetLocations(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetLocations_Call {
	return &ClusterManagerServer_SetLocations_Call{Call: _e.mock.On("SetLocations", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetLocations_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetLocationsRequest)) *ClusterManagerServer_SetLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetLocationsRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetLocations_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetLoggingService provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetLoggingService(_a0 context.Context, _a1 *containerpb.SetLoggingServiceRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetLoggingServiceRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetLoggingServiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetLoggingService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLoggingService'
type ClusterManagerServer_SetLoggingService_Call struct {
	*mock.Call
}

// SetLoggingService is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetLoggingServiceRequest
func (_e *ClusterManagerServer_Expecter) SetLoggingService(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetLoggingService_Call {
	return &ClusterManagerServer_SetLoggingService_Call{Call: _e.mock.On("SetLoggingService", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetLoggingService_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetLoggingServiceRequest)) *ClusterManagerServer_SetLoggingService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetLoggingServiceRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetLoggingService_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetLoggingService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetMaintenancePolicy provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetMaintenancePolicy(_a0 context.Context, _a1 *containerpb.SetMaintenancePolicyRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetMaintenancePolicyRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetMaintenancePolicyRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetMaintenancePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaintenancePolicy'
type ClusterManagerServer_SetMaintenancePolicy_Call struct {
	*mock.Call
}

// SetMaintenancePolicy is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetMaintenancePolicyRequest
func (_e *ClusterManagerServer_Expecter) SetMaintenancePolicy(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetMaintenancePolicy_Call {
	return &ClusterManagerServer_SetMaintenancePolicy_Call{Call: _e.mock.On("SetMaintenancePolicy", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetMaintenancePolicy_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetMaintenancePolicyRequest)) *ClusterManagerServer_SetMaintenancePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetMaintenancePolicyRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetMaintenancePolicy_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetMaintenancePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetMasterAuth provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetMasterAuth(_a0 context.Context, _a1 *containerpb.SetMasterAuthRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetMasterAuthRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetMasterAuthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetMasterAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMasterAuth'
type ClusterManagerServer_SetMasterAuth_Call struct {
	*mock.Call
}

// SetMasterAuth is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetMasterAuthRequest
func (_e *ClusterManagerServer_Expecter) SetMasterAuth(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetMasterAuth_Call {
	return &ClusterManagerServer_SetMasterAuth_Call{Call: _e.mock.On("SetMasterAuth", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetMasterAuth_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetMasterAuthRequest)) *ClusterManagerServer_SetMasterAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetMasterAuthRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetMasterAuth_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetMasterAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetMonitoringService provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetMonitoringService(_a0 context.Context, _a1 *containerpb.SetMonitoringServiceRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetMonitoringServiceRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetMonitoringServiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetMonitoringService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMonitoringService'
type ClusterManagerServer_SetMonitoringService_Call struct {
	*mock.Call
}

// SetMonitoringService is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetMonitoringServiceRequest
func (_e *ClusterManagerServer_Expecter) SetMonitoringService(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetMonitoringService_Call {
	return &ClusterManagerServer_SetMonitoringService_Call{Call: _e.mock.On("SetMonitoringService", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetMonitoringService_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetMonitoringServiceRequest)) *ClusterManagerServer_SetMonitoringService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetMonitoringServiceRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetMonitoringService_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetMonitoringService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetNetworkPolicy provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetNetworkPolicy(_a0 context.Context, _a1 *containerpb.SetNetworkPolicyRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetNetworkPolicyRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetNetworkPolicyRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetNetworkPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNetworkPolicy'
type ClusterManagerServer_SetNetworkPolicy_Call struct {
	*mock.Call
}

// SetNetworkPolicy is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetNetworkPolicyRequest
func (_e *ClusterManagerServer_Expecter) SetNetworkPolicy(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetNetworkPolicy_Call {
	return &ClusterManagerServer_SetNetworkPolicy_Call{Call: _e.mock.On("SetNetworkPolicy", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetNetworkPolicy_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetNetworkPolicyRequest)) *ClusterManagerServer_SetNetworkPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetNetworkPolicyRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetNetworkPolicy_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetNetworkPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetNodePoolAutoscaling provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetNodePoolAutoscaling(_a0 context.Context, _a1 *containerpb.SetNodePoolAutoscalingRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetNodePoolAutoscalingRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetNodePoolAutoscalingRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetNodePoolAutoscaling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodePoolAutoscaling'
type ClusterManagerServer_SetNodePoolAutoscaling_Call struct {
	*mock.Call
}

// SetNodePoolAutoscaling is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetNodePoolAutoscalingRequest
func (_e *ClusterManagerServer_Expecter) SetNodePoolAutoscaling(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetNodePoolAutoscaling_Call {
	return &ClusterManagerServer_SetNodePoolAutoscaling_Call{Call: _e.mock.On("SetNodePoolAutoscaling", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetNodePoolAutoscaling_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetNodePoolAutoscalingRequest)) *ClusterManagerServer_SetNodePoolAutoscaling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetNodePoolAutoscalingRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetNodePoolAutoscaling_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetNodePoolAutoscaling_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetNodePoolManagement provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetNodePoolManagement(_a0 context.Context, _a1 *containerpb.SetNodePoolManagementRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetNodePoolManagementRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetNodePoolManagementRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetNodePoolManagement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodePoolManagement'
type ClusterManagerServer_SetNodePoolManagement_Call struct {
	*mock.Call
}

// SetNodePoolManagement is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetNodePoolManagementRequest
func (_e *ClusterManagerServer_Expecter) SetNodePoolManagement(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetNodePoolManagement_Call {
	return &ClusterManagerServer_SetNodePoolManagement_Call{Call: _e.mock.On("SetNodePoolManagement", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetNodePoolManagement_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetNodePoolManagementRequest)) *ClusterManagerServer_SetNodePoolManagement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetNodePoolManagementRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetNodePoolManagement_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetNodePoolManagement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetNodePoolSize provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) SetNodePoolSize(_a0 context.Context, _a1 *containerpb.SetNodePoolSizeRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.SetNodePoolSizeRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.SetNodePoolSizeRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_SetNodePoolSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodePoolSize'
type ClusterManagerServer_SetNodePoolSize_Call struct {
	*mock.Call
}

// SetNodePoolSize is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.SetNodePoolSizeRequest
func (_e *ClusterManagerServer_Expecter) SetNodePoolSize(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_SetNodePoolSize_Call {
	return &ClusterManagerServer_SetNodePoolSize_Call{Call: _e.mock.On("SetNodePoolSize", _a0, _a1)}
}

func (_c *ClusterManagerServer_SetNodePoolSize_Call) Run(run func(_a0 context.Context, _a1 *containerpb.SetNodePoolSizeRequest)) *ClusterManagerServer_SetNodePoolSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.SetNodePoolSizeRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_SetNodePoolSize_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_SetNodePoolSize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// StartIPRotation provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) StartIPRotation(_a0 context.Context, _a1 *containerpb.StartIPRotationRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.StartIPRotationRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.StartIPRotationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_StartIPRotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartIPRotation'
type ClusterManagerServer_StartIPRotation_Call struct {
	*mock.Call
}

// StartIPRotation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.StartIPRotationRequest
func (_e *ClusterManagerServer_Expecter) StartIPRotation(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_StartIPRotation_Call {
	return &ClusterManagerServer_StartIPRotation_Call{Call: _e.mock.On("StartIPRotation", _a0, _a1)}
}

func (_c *ClusterManagerServer_StartIPRotation_Call) Run(run func(_a0 context.Context, _a1 *containerpb.StartIPRotationRequest)) *ClusterManagerServer_StartIPRotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.StartIPRotationRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_StartIPRotation_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_StartIPRotation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateCluster provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) UpdateCluster(_a0 context.Context, _a1 *containerpb.UpdateClusterRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.UpdateClusterRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.UpdateClusterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_UpdateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCluster'
type ClusterManagerServer_UpdateCluster_Call struct {
	*mock.Call
}

// UpdateCluster is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.UpdateClusterRequest
func (_e *ClusterManagerServer_Expecter) UpdateCluster(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_UpdateCluster_Call {
	return &ClusterManagerServer_UpdateCluster_Call{Call: _e.mock.On("UpdateCluster", _a0, _a1)}
}

func (_c *ClusterManagerServer_UpdateCluster_Call) Run(run func(_a0 context.Context, _a1 *containerpb.UpdateClusterRequest)) *ClusterManagerServer_UpdateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.UpdateClusterRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_UpdateCluster_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_UpdateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateMaster provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) UpdateMaster(_a0 context.Context, _a1 *containerpb.UpdateMasterRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.UpdateMasterRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.UpdateMasterRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_UpdateMaster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMaster'
type ClusterManagerServer_UpdateMaster_Call struct {
	*mock.Call
}

// UpdateMaster is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.UpdateMasterRequest
func (_e *ClusterManagerServer_Expecter) UpdateMaster(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_UpdateMaster_Call {
	return &ClusterManagerServer_UpdateMaster_Call{Call: _e.mock.On("UpdateMaster", _a0, _a1)}
}

func (_c *ClusterManagerServer_UpdateMaster_Call) Run(run func(_a0 context.Context, _a1 *containerpb.UpdateMasterRequest)) *ClusterManagerServer_UpdateMaster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.UpdateMasterRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_UpdateMaster_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_UpdateMaster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateNodePool provides a mock function with given fields: _a0, _a1
func (_m *ClusterManagerServer) UpdateNodePool(_a0 context.Context, _a1 *containerpb.UpdateNodePoolRequest) (*containerpb.Operation, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *containerpb.Operation
	if rf, ok := ret.Get(0).(func(context.Context, *containerpb.UpdateNodePoolRequest) *containerpb.Operation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerpb.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *containerpb.UpdateNodePoolRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterManagerServer_UpdateNodePool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNodePool'
type ClusterManagerServer_UpdateNodePool_Call struct {
	*mock.Call
}

// UpdateNodePool is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *containerpb.UpdateNodePoolRequest
func (_e *ClusterManagerServer_Expecter) UpdateNodePool(_a0 interface{}, _a1 interface{}) *ClusterManagerServer_UpdateNodePool_Call {
	return &ClusterManagerServer_UpdateNodePool_Call{Call: _e.mock.On("UpdateNodePool", _a0, _a1)}
}

func (_c *ClusterManagerServer_UpdateNodePool_Call) Run(run func(_a0 context.Context, _a1 *containerpb.UpdateNodePoolRequest)) *ClusterManagerServer_UpdateNodePool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*containerpb.UpdateNodePoolRequest))
	})
	return _c
}

func (_c *ClusterManagerServer_UpdateNodePool_Call) Return(_a0 *containerpb.Operation, _a1 error) *ClusterManagerServer_UpdateNodePool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewClusterManagerServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterManagerServer creates a new instance of ClusterManagerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterManagerServer(t mockConstructorTestingTNewClusterManagerServer) *ClusterManagerServer {
	mock := &ClusterManagerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
