package bootstrap

import (
	"fmt"
	config "github.com/broadinstitute/thelma/internal/thelma/app/config"
	"github.com/broadinstitute/thelma/internal/thelma/app/root"
	"github.com/broadinstitute/thelma/internal/thelma/utils/prompt/mocks"
	"github.com/broadinstitute/thelma/internal/thelma/utils/shell"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/stretchr/testify/suite"
	"os"
	"path"
	"strings"
	"testing"
)

// Define the suite, and absorb the built-in basic suite
// functionality from testify - including a T() method which
// returns the current testing context
type BootstrapSuite struct {
	suite.Suite
	root                      root.Root
	config                    config.Config
	runner                    *shell.MockRunner
	prompt                    *mocks.Prompt
	bootstrapper              Bootstrapper
	zshrcPath                 string
	configFilePath            string
	shellCompletionScriptPath string
	initScriptPath            string
}

// Make sure that VariableThatShouldStartAtFive is set to five
// before each test
func (suite *BootstrapSuite) SetupTest() {
	var err error

	t := suite.T()
	suite.root = root.NewAt(t.TempDir())
	require.NoError(t, suite.root.CreateDirectories())

	suite.config, err = config.NewTestConfig(t)
	require.NoError(t, err)

	suite.runner = shell.DefaultMockRunner()
	suite.prompt = mocks.NewPrompt(t)
	suite.zshrcPath = path.Join(t.TempDir(), zshrcFile)

	suite.bootstrapper = newWith(suite.root, suite.config, suite.runner, suite.prompt, suite.zshrcPath)

	suite.configFilePath = path.Join(suite.root.Dir(), "config.yaml")
	suite.shellCompletionScriptPath = path.Join(suite.root.ShellDir(), thelmaShellCompletionFile)
	suite.initScriptPath = path.Join(suite.root.ShellDir(), thelmaInitializationFile)
}

func (suite *BootstrapSuite) TestBootstrapFullInstallWithDefaults() {
	suite.setUserInputAddToolsToPath(true)
	suite.setUserInputShellCompletion(true)
	suite.expectShellCompletionCommand("fake shell completion script")

	require.NoError(suite.T(), suite.bootstrapper.Bootstrap())

	suite.verifyConfigFile()
	suite.verifyShellCompletionScript("fake shell completion script")
	suite.verifyInitScript(`#
# Thelma shell initialization file
#
# This file was auto-generated by +thelma update --bootstrap+; do not edit!
#

# Add +thelma+ to PATH
export PATH="<ROOT>/releases/current/bin:${PATH}"

# Add Thelma bundled tools (helmfile, helm, kubectl, etc) to PATH
export PATH="<ROOT>/releases/current/tools/bin:${PATH}"

# Enable shell completion for +thelma+
source <ROOT>/shell/completion.zsh && compdef _thelma thelma
`)
	suite.verifyZshrcUpdated()
}

func (suite *BootstrapSuite) TestBootstrapDoesNotAddShellCompletionIfNotSelected() {
	suite.setUserInputAddToolsToPath(true)
	suite.setUserInputShellCompletion(false)

	require.NoError(suite.T(), suite.bootstrapper.Bootstrap())

	assert.NoFileExists(suite.T(), suite.shellCompletionScriptPath)

	suite.assertFileContent(suite.initScriptPath, `#
# Thelma shell initialization file
#
# This file was auto-generated by +thelma update --bootstrap+; do not edit!
#

# Add +thelma+ to PATH
export PATH="<ROOT>/releases/current/bin:${PATH}"

# Add Thelma bundled tools (helmfile, helm, kubectl, etc) to PATH
export PATH="<ROOT>/releases/current/tools/bin:${PATH}"
`)
}

func (suite *BootstrapSuite) TestBootstrapDoesNotAddToolsToPathIfNotSelected() {
	suite.setUserInputAddToolsToPath(false)
	suite.setUserInputShellCompletion(true)
	suite.expectShellCompletionCommand("fake shell completion script")

	require.NoError(suite.T(), suite.bootstrapper.Bootstrap())

	suite.assertFileContent(suite.initScriptPath, `#
# Thelma shell initialization file
#
# This file was auto-generated by +thelma update --bootstrap+; do not edit!
#

# Add +thelma+ to PATH
export PATH="<ROOT>/releases/current/bin:${PATH}"

# Enable shell completion for +thelma+
source <ROOT>/shell/completion.zsh && compdef _thelma thelma
`)
}

func (suite *BootstrapSuite) TestBootstrapDoesNotAddToolsToPathOrAddShellCompletionIfNotSelected() {
	suite.setUserInputAddToolsToPath(false)
	suite.setUserInputShellCompletion(false)

	require.NoError(suite.T(), suite.bootstrapper.Bootstrap())

	suite.verifyInitScript(`#
# Thelma shell initialization file
#
# This file was auto-generated by +thelma update --bootstrap+; do not edit!
#

# Add +thelma+ to PATH
export PATH="<ROOT>/releases/current/bin:${PATH}"
`)
}

func (suite *BootstrapSuite) TestBootstrapBacksUpZshrc() {
	suite.setUserInputAddToolsToPath(false)
	suite.setUserInputShellCompletion(false)

	content := []byte("A fake zshrc with stuff in it\n")
	err := os.WriteFile(suite.zshrcPath, content, 0644)
	require.NoError(suite.T(), err)

	require.NoError(suite.T(), suite.bootstrapper.Bootstrap())

	zshrcDir := path.Dir(suite.zshrcPath)
	entries, err := os.ReadDir(zshrcDir)
	require.NoError(suite.T(), err)
	assert.Equal(suite.T(), 2, len(entries))

	backupFile := path.Join(zshrcDir, entries[1].Name())
	assert.Regexp(suite.T(), `.*\/\.zshrc.\d{8}\.\d{6}$`, backupFile)

	suite.assertFileContent(backupFile, "A fake zshrc with stuff in it\n")
}

// In order for 'go test' to run this suite, we need to create
// a normal test function and pass our suite to suite.Run
func TestBootstrapper(t *testing.T) {
	suite.Run(t, new(BootstrapSuite))
}

func (suite *BootstrapSuite) setUserInputShellCompletion(shellCompletion bool) {
	suite.prompt.EXPECT().Confirm(enableShellCompletionPrompt, true).Return(shellCompletion, nil)
}

func (suite *BootstrapSuite) setUserInputAddToolsToPath(addToolsToPath bool) {
	suite.prompt.EXPECT().Confirm(addToolsToPathPrompt, true).Return(addToolsToPath, nil)
}

func (suite *BootstrapSuite) expectShellCompletionCommand(output string) {
	executable, err := root.PathToRunningThelmaExecutable()
	require.NoError(suite.T(), err)
	suite.runner.ExpectCmd(shell.Command{
		Prog: executable,
		Args: []string{"completion", "zsh"},
	}).WithStdout(output)
}

func (suite *BootstrapSuite) verifyConfigFile() {
	suite.assertFileContent(suite.configFilePath, fmt.Sprintf(`#
# Thelma configuration file
#

# path to terra-helmfile git clone
home: %s
`, suite.config.Home()))
}

func (suite *BootstrapSuite) verifyShellCompletionScript(content string) {
	suite.assertFileContent(suite.shellCompletionScriptPath, content)
}

func (suite *BootstrapSuite) verifyInitScript(content string) {
	suite.assertFileContent(suite.initScriptPath, content)
}

func (suite *BootstrapSuite) verifyZshrcUpdated() {
	assert.FileExists(suite.T(), suite.zshrcPath)

	expectedFragment := suite.normalizeTestFileContent(`
# Thelma initialization
if [ -f "<ROOT>/shell/init.zsh" ]; then . "<ROOT>/shell/init.zsh"; fi

`)

	actualContent, err := os.ReadFile(suite.zshrcPath)
	require.NoError(suite.T(), err)

	assert.Contains(suite.T(), string(actualContent), expectedFragment)
}

func (suite *BootstrapSuite) assertFileContent(file string, expectedContent string) {
	assert.FileExists(suite.T(), file)

	content, err := os.ReadFile(file)
	require.NoError(suite.T(), err)

	expectedContent = suite.normalizeTestFileContent(expectedContent)

	assert.Equal(suite.T(), expectedContent, string(content), "%s has incorrect content", file)
}

func (suite *BootstrapSuite) normalizeTestFileContent(expectedContent string) string {
	// replace + with ` since some templates contain ` and we
	// can't use ` in raw string literals
	expectedContent = strings.ReplaceAll(expectedContent, "+", "`")

	// replace <ROOT> with our test's fake thelma root dir (randomly generated)
	expectedContent = strings.ReplaceAll(expectedContent, "<ROOT>", suite.root.Dir())
	return expectedContent
}
