name: Run Unit Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: run tests
      uses: ./.github/actions/make
      with:
        target: "test"
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        files: ./output/coverage
        flags: unittests
