name: Run Unit & Smoke Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
        service_account: 'thelma-ci@dsp-tools-k8s.iam.gserviceaccount.com'

    - name: Run tests
      uses: ./.github/actions/make
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        target: "smoke"

    - name: Run tests (dependabot)
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: ./.github/actions/make
      with:
        # Dependabot can't run smoke tests but unit tests are better than nothing
        target: "test"

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        files: ./output/coverage
        flags: unittests

