name: Run Unit & Smoke Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCP auth
      if: ${{ github.actor != 'dependabot[bot]' }}
      id: setup-gcp-auth
      run: |
        GCP_CREDS_PATH=$(pwd)/service_account.json
        echo '${{ secrets.THELMA_CI_KEY }}' > service_account.json
        echo gcp-creds-path=${GCP_CREDS_PATH} >> $GITHUB_OUTPUT

    - name: Run tests
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: ./.github/actions/make
      with:
        target: "smoke"
      env:
        # Some smoke tests use GCP credentials
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.setup-gcp-auth.outputs.gcp-creds-path }}

    - name: Run tests (dependabot)
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: ./.github/actions/make
      with:
        # Dependabot can't run smoke tests but unit tests are better than nothing
        target: "test"

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        files: ./output/coverage
        flags: unittests
