name: Run Unit Tests
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCP auth
      run: echo '${{ secrets.THELMA_CI_KEY }}' > service_account.json

    - name: Run tests
      uses: ./.github/actions/make
      with:
        target: "smoke"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: service_account.json

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1
      with:
        files: ./output/coverage
        flags: unittests
